### ISSUE TITLE
TeslaException - Suddenly stopped working this afternoon

### ISSUE THREAD

**Issue by kimme1024** [flashg1/TeslaSolarCharger#22]
Except for some minor hiccups which can be fixed with other automations, this blueprint has been working perfect for about 8 months now! Thanks for that!

However today the script stopped working, when I restarted it quits after some time with an error (see image below)
![Scherm­afbeelding 2024-06-14 om 13 18 37](https://github.com/flashg1/TeslaSolarCharger/assets/42653485/42d2e852-c834-41a0-a421-dfae2121d667)

I fear it's on the Tesla-side of things but any idea's on how to fix this are always welcome!
I can pull data from the car without any issues but I can't send anything. Changing the amps manually is returning an unknown error.

Thanks!

**Comment by kimme1024** [comment]
Unplugging and MCU-reset fixed the issue for now...

**Comment by kimme1024** [comment]
Failed again today…
Anyone else with this issue?

I also noticed that in the Tesla app, I can’t set the amps below 5. Maybe that’s what’s causing the issue. 

I also tested setting amps above 5 but I still can’t send anything to the car.

**Comment by flashg1** [comment]
Which version of custom Tesla integration are you using?  Are you using the Tesla Fleet API Proxy?  More info here:  https://github.com/alandtse/tesla

Any more clue about the exception message?  Do you know which API call triggered the exception?

**Comment by kimme1024** [comment]
> Which version of custom Tesla integration are you using? Are you using the Tesla Fleet API Proxy? More info here: https://github.com/alandtse/tesla
> 
> Any more clue about the exception message? Do you know which API call triggered the exception?

I’m using the latest integration
I don’t use the fleet api and I don't think I'll have to use it. Yesterday, after resetting the MCU it started working again. If I would have switched to the fleet API this shouldn't have been possible (or am I wrong in this?)
Any idea on how to retrieve the extra info?

**Comment by kimme1024** [comment]
Just tried resetting my MCU but that didn't solve the issue.

Checked the logs:

```
Logger: homeassistant.components.automation.tesla_solar_charger
Bron: components/automation/__init__.py:723
integratie: Automatisering (documentatie, problemen)
Eerst voorgekomen: 09:46:46 (6 gebeurtenissen)
Laatst gelogd: 16:05:05

While executing automation automation.tesla_solar_charger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 723, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/trace.py", line 284, in async_wrapper
    await func(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 952, in _async_repeat_step
    await async_run_sequence(iteration)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 856, in async_run_sequence
    await self._async_run_script(script)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1210, in _async_run_script
    result = await self._async_run_long_action(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1016, in _async_choose_step
    await self._async_run_script(script)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1210, in _async_run_script
    result = await self._async_run_long_action(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1016, in _async_choose_step
    await self._async_run_script(script)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1210, in _async_run_script
    result = await self._async_run_long_action(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1043, in _async_if_step
    await self._async_run_script(if_data["if_then"])
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1210, in _async_run_script
    result = await self._async_run_long_action(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 116, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/tesla_custom/number.py", line 91, in async_set_native_value
    await self._car.set_charging_amps(value)
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 934, in set_charging_amps
    data = await self._send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 785, in _send_command
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 770, in _send_command
    data = await self._controller.api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1361, in api
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1355, in api
    response = await self.__post_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 142, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 58, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 110, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 78, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 61, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1390, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException

```


```
Logger: homeassistant.components.automation.tesla_solar_charger
Bron: helpers/script.py:501
integratie: Automatisering (documentatie, problemen)
Eerst voorgekomen: 09:46:46 (27 gebeurtenissen)
Laatst gelogd: 16:05:05

Tesla Solar Charger: Repeat at step 7: Choose at step 3: choice 1: Error executing script. Unexpected error for choose at pos 1:
Tesla Solar Charger: Repeat at step 7: Error executing script. Unexpected error for choose at pos 3:
Tesla Solar Charger: Error executing script. Unexpected error for repeat at pos 7:
Tesla Solar Charger: Repeat at step 7: Choose at step 3: choice 4: Repeat at step 1: Error executing script. Unexpected error for call_service at pos 1:
Tesla Solar Charger: Repeat at step 7: Choose at step 3: choice 4: Error executing script. Unexpected error for repeat at pos 1:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 116, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/tesla_custom/number.py", line 91, in async_set_native_value
    await self._car.set_charging_amps(value)
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 934, in set_charging_amps
    data = await self._send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 785, in _send_command
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 770, in _send_command
    data = await self._controller.api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1361, in api
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1355, in api
    response = await self.__post_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 142, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 58, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 110, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 78, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 61, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1390, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException

```



```
Logger: homeassistant.components.websocket_api.http.connection
Bron: components/websocket_api/commands.py:239
integratie: Home Assistant WebSocket API (documentatie, problemen)
Eerst voorgekomen: 09:46:54 (5 gebeurtenissen)
Laatst gelogd: 16:03:19

[281471817408960] Unexpected exception
[281471556068928] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 116, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/tesla_custom/number.py", line 91, in async_set_native_value
    await self._car.set_charging_amps(value)
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 934, in set_charging_amps
    data = await self._send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 785, in _send_command
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 770, in _send_command
    data = await self._controller.api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1361, in api
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1355, in api
    response = await self.__post_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 142, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 58, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 110, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 78, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 61, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1390, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException

```

```
Logger: asyncio
Bron: components/websocket_api/http.py:155
Eerst voorgekomen: 12:49:18 (8 gebeurtenissen)
Laatst gelogd: 13:57:38

socket.send() raised exception.
```

**Comment by flashg1** [comment]
Is there a config to stay with the Owner API?  Or is that the default?

To stay with the Owner API, you might need to reauthenticate, or try revert to your previous version of Tesla integration.

**Comment by kimme1024** [comment]
> Is there a config to stay with the Owner API? Or is that the default?
> 
> To stay with the Owner API, you might need to reauthenticate, or try revert to your previous version of Tesla integration.

I never had to reconfigure when the fleet api was released.

I’ll try to reauth and report back.

**Comment by kimme1024** [comment]
Removed and readded integration.
Only thing I had to do was not to select fleet api so I guess this is the standard way.
Sadly reauth didn’t fix the issue.
Car seems to be read only…

**Comment by kimme1024** [comment]
Weird, this morning. Without changing anything it started working again…

**Comment by stieler-it** [comment]
I have setup the automation today, I also see a TeslaException with the following stacktrace:

```
...
  File "/config/custom_components/tesla_custom/number.py", line 91, in async_set_native_value
    await self._car.set_charging_amps(value)
...
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
    raise TeslaException(resp.status_code)
```

This is for Tesla custom addon, without proxy, MY 2024.

When I decrease the charging power manually it works but something (the script?) sets it back to full power.

**Comment by kimme1024** [comment]
> I have setup the automation today, I also see a TeslaException with the following stacktrace:
> 
> ```
> ...
>   File "/config/custom_components/tesla_custom/number.py", line 91, in async_set_native_value
>     await self._car.set_charging_amps(value)
> ...
>   File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
>     return await self.__open(url, method=method, headers=self.head, data=data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
>     raise TeslaException(resp.status_code)
> ```
> 
> This is for Tesla custom addon, without proxy, MY 2024.
> 
> When I decrease the charging power manually it works but something (the script?) sets it back to full power.

Maybe something wrong with the sensor that measures the excess solar? W instead of kW? Had this issue in the beginning as well.

**Comment by stieler-it** [comment]
> W instead of kW?

Thank you, converting W to kW in my grid sensor helped fixing the TeslaException. Automation now keeps running, triggers force update from time to time, so far it did not change charging power, even if 2kW are pulled from the grid. But that's a good point to start debugging from, thank you.

**Comment by stieler-it** [comment]
Ok just wanted to give an update. I found out that TeslaException was expected since I needed to setup Tesla HTTP Proxy to be able to send commands to the vehicle at all. I missed that part in Tesla custom integration. My template sensor with "kW" instead of watts seems not to be needed, I think TeslaSolarCharger even requires watts to work correctly.
Now at least the blueprint works, but only for a while. After a few corrections of the charging ampere, I am back to TeslaExceptions, so I now assume I am hitting the Tesla rate limits quite fast. Unfortunately this makes the whole approach not usable for me.
I know replaced it with a simple "as soon as we feed-in 2kW, start charging" and "as soon as sunset, stop charging" logic. Which is not very satisfying but better than nothing.
Anybody else problems with rate limits?

**Comment by stieler-it** [comment]
Ok I re-tested the automation today and my observations boil down to a improvement idea. I think there is kinf of a rate limit around Tesla API and calling it too often leads to the TeslaException and the script being terminated (leaving everything in an undefined state).

What I observed today:

1. Car was charging with 13 Amps (max power on outlet)
2. Sun power dropped rather quickly
3. 13:09:32 charger amps decreased to 12
4. 13:09:37 charger amps decreased to 11
5. 13:09:43 charger amps decreased to 10
6. 13:09:48 charger amps decreased to 9
7. 13:09:53 charger amps decreased to 8 <- this fails with a TeslaException

So the automation tried to send at least 5 calls to the API in 21 seconds.

Now I have two ideas how this could be improved:

1. Change the logic to go from 12 to say 4 amps immediately. All data should be available to calculate the best charging amps at any point without going there step-by-step
2. Configure a local rate limit or simply loop every 30 seconds instead of every 5. I will try to change this in the blueprint and check if it fixes my setup

Update: Ok with a limit of apparently 50 commands per day both approaches would not fix it completey. There is also an interesting discussion on Reddit: https://www.reddit.com/r/homeassistant/comments/1dixaub/tesla_fleet_api_request_limits_how_are_you_coping/

**Comment by flashg1** [comment]
5 calls in 21 seconds is a lifetime.  I doubt anything can work with 50 commands per day.  I have been using this for over a year now with no issues.  WIFI network stability and cloud connectivity can cause Tesla API exceptions.

Please note that by default the script loops once every 60 seconds.

**Comment by stieler-it** [comment]
> I doubt anything can work with 50 commands per day

Yes, let's hope Tesla offers something that allows us to do more calls again. I now switched to two very basic automations, which boil down to: When feed-in is > threshold for 5 minutes, then start charging. When consumption from net is > other threshold (like 1 kW) for 5 minutes, then stop charging. This means that it can happen that for a few minutes I charge more than I have or less then I could but this is not an issue for me - at least in summer. And so far I never reached the API limit.

**Comment by perjmolsen** [comment]
Hi

Just a tip from me :)

You can communicate directly with your tesla thru Bluetooth, I am using it on my Tesla model 3 highland.

I have flashed a wemos d1 mini board with tesla ble - then I am able to adjust charging amps directly from HA, and keep all my traffic local.

![Tesla BLE](https://github.com/user-attachments/assets/efae8210-afb4-4f64-ba05-f0c617e96186)

Tesla ble can be found here: https://github.com/yoziru/esphome-tesla-ble

**Comment by stieler-it** [comment]
> You can communicate directly with your tesla thru Bluetooth

Thank you, I didn't know there is already an ESPHome integration. I think I have some ESPs left, will try it, this would be a lot better than my current solution.

**Comment by perjmolsen** [comment]
You are welcome :) 
Tesla BLE works perfect  with Tesla Solar charger script.

**Comment by flashg1** [comment]
> Hi
> 
> Just a tip from me :)
> 
> You can communicate directly with your tesla thru Bluetooth, I am using it on my Tesla model 3 highland.
> 
> I have flashed a wemos d1 mini board with tesla ble - then I am able to adjust charging amps directly from HA, and keep all my traffic local.
> 
> ![Tesla BLE](https://private-user-images.githubusercontent.com/126662740/386157501-efae8210-afb4-4f64-ba05-f0c617e96186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MjczNTEsIm5iZiI6MTczMTYyNzA1MSwicGF0aCI6Ii8xMjY2NjI3NDAvMzg2MTU3NTAxLWVmYWU4MjEwLWFmYjQtNGY2NC1iYTA1LWYwYzYxN2U5NjE4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQyMzMwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmRlOTc5MmRkOWNmNWJiYWY0NTU3MzlhOTc1NWI0MWQyYmNhNzIzZWYyOTU4Y2JkYjQxNWMwZDU5NWMyMWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aw53kvZ3grYQziIVZjR6emKPipHjCzaaA0yzHtiJSXo)
> 
> Tesla ble can be found here: https://github.com/yoziru/esphome-tesla-ble

Thank you for the tip.

**Comment by flashg1** [comment]
Closing case unless this is still an issue.
